---
version: '2'
services:

  postgresql:
    image: postgres
    networks:
      - common-network
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=securitydb
  nocta-api:
    container_name: nocta-api
    build:
      context: nocta-api
      dockerfile: Dockerfile
    image: nocta-api:latest
    ports:
      - 8080:8080
    networks:
      - common-network
    depends_on:
      - postgresql
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgresql:5432/securitydb
networks:
  common-network:
    driver: bridge